inherit_from:
  - https://gist.githubusercontent.com/pat/ba3b8ffb1901bfe5439b460943b6b019/raw/.rubocop.yml

AllCops:
  TargetRubyVersion: 2.2

Style/Documentation:
  Enabled: false

Style/RedundantFreeze:
  Enabled: false

Style/SafeNavigation:
  Enabled: false
